{% set name = "sregistry" %}
{% set version = "0.2.39" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: db8805e963d34a4fbda329c08d2e913667e01f8ed1511e6597dc8cc4b3ce6d24

build:
  number: 0
  entry_points:
    - sregistry=sregistry.client:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  skip: true  # [win or py2k]

requirements:
  host:
    - pip
    - pytest-runner
    - python
    - setuptools
  run:
    - pygments >=2.1.3
    - python
    - requests >=2.18.4
    - sqlalchemy
    - spython

test:
  imports:
    - sregistry
    - sregistry.auth
    - sregistry.client
    - sregistry.database
    - sregistry.logger
    - sregistry.main
    - sregistry.main.base
    - sregistry.main.docker
    - sregistry.main.gitlab
    - sregistry.main.hub
    - sregistry.main.nvidia
    - sregistry.main.templates
    - sregistry.main.templates.build
    - sregistry.main.workers
    - sregistry.tests
    - sregistry.utils
  commands:
    - sregistry --help

outputs:
  - name: sregistry

  - name: sregistry-registry
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('sregistry', exact=True) }}
        - python-dateutil >=2.5.3
        - requests-toolbelt >=0.8.0
    test:
      imports:
        - sregistry.main.registry
  - name: sregistry-aws
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('sregistry', exact=True) }}
        - awscli >=1.16.19
    test:
      imports:
        - sregistry.main.aws
  - name: sregistry-swift
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('sregistry', exact=True) }}
        - python-swiftclient >=3.6.0
        - python-keystoneclient >=3.5.0
        - oauth2client >=3.0
    test:
      imports:
        - sregistry.main.swift
  - name: sregistry-dropbox
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('sregistry', exact=True) }}
        - dropbox >=8.5.1
    test:
      imports:
        - sregistry.main.dropbox
  - name: sregistry-globus
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('sregistry', exact=True) }}
        - oauth2client >=3.0
        - globus-sdk >=1.5.0
    test:
      imports:
        - sregistry.main.globus
  - name: sregistry-google-storage
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('sregistry', exact=True) }}
        - oauth2client >=3.0
        - google-cloud-storage >=1.4.0
        - retrying >=1.3.3
        - google-api-python-client >=1.6.4
        - httplib2
    test:
      imports:
        - sregistry.main.google_storage
  - name: sregistry-google-build
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('sregistry', exact=True) }}
        - oauth2client >=3.0
        - google-cloud-storage >=1.4.0
        - retrying >=1.3.3
        - google-api-python-client >=1.6.4
        - httplib2
    test:
      imports:
        - sregistry.main.google_build
  - name: sregistry-google-drive
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('sregistry', exact=True) }}
        - oauth2client >=3.0
        - google-api-python-client >=1.6.4
        - httplib2
    test:
      imports:
        - sregistry.main.google_drive
  - name: sregistry-google-compute
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('sregistry', exact=True) }}
        - oauth2client >=3.0
        - google-api-python-client >=1.6.4
        - google-cloud-storage >=1.4.0
        - retrying >=1.3.3
        - httplib2
    test:
      imports:
        - sregistry.main.google_storage
  - name: sregistry-s3
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('sregistry', exact=True) }}
        - boto3 >=1.7.83
    test:
      imports:
        - sregistry.main.s3

about:
  home: https://github.com/singularityhub/sregistry-cli
  license: MPL-2.0
  license_family: OTHER
  license_file: LICENSE
  summary: Command line tool for working with container storage
  doc_url: https://singularityhub.github.io/sregistry-cli
  dev_url: https://github.com/singularityhub/sregistry-cli

extra:
  recipe-maintainers:
    - tschoonj
    - vsoch
