travis:
  secure:
    BINSTAR_TOKEN: ynv82pz4aP6pu4K7vaAYgj0rzTTFkAxKWDAkBQqeME9ZS7Zsw0nSTvvAJ387TYKaFIzdkukamIG5tGTH7gWQvw9iOwVIN5bUFketwE0c1rML2pmg6yI2k+xfz105HNo40XDN5c0s+XVF7PX43Z4qmbdkEjQirv4Kcx3ba8oMyVWoPq+dMBv0RdBUSFEGu4+TfhohAKw3f/6HggtzwmJ009cvxvoquvjGmgnFfquMeCrWBDyQ7te3W+l9Rlweh/VwFTTJLS1mA0jbsoyapWCI89CnqA910TXv4IyKC6XjG2r7lD2qRHuZ4SFgUByynzyGaC9gBrkX14HpYs20S2t+dCV2mmscV7j0sxO6XJ1UYWiZ6GG6kq5Ci7kaf8h95YaCXPo01ff/YX8RuMAKCc4e63lj6lgZq1pWKFDPAq5FHsQbF5NeMD6llwvL7wdxS0TrZfhRUbxupfwtFtw3HEO2Uwhtob/fw3o3Ia3Yvy8V++IvguIESZBfThgaaMreJ6gZdjK58+eXYtv+3zkX2ewjBL4JDqFE/vTgAM1dywrEXLeuf/qV4ij9GL2Xus108Ee/yksxXyxw/d1LsrndZ10Mgt0YmM/wuXYY+W4kxzbXhoapBKtGJVHV6mQiG6QDMX3z6Gcu73vVNf8fK+WRi8m3eho0LeVIrNFOATT6SlvmGlE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
